import { createFileRoute, Link, notFound } from '@tanstack/react-router';
import { ArrowLeft, ArrowRight, Check, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { VehicleCard } from '@/components/auto/vehicle-card';
import { allVehicles, formatPrice, vehicleImage, vehicles } from '@/data/vehicles';
import { pageHead } from '@/lib/seo';
const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-');
export const Route=createFileRoute('/cars/$brand/$model')({
 loader:({params})=>{const vehicle=allVehicles.find(v=>slug(v.brand)===params.brand&&slug(v.model)===params.model);if(!vehicle)throw notFound();return {vehicle}},
 head:({loaderData})=>loaderData?pageHead(`${loaderData.vehicle.brand} ${loaderData.vehicle.model} in Pakistan | Motori`,`Explore the ${loaderData.vehicle.brand} ${loaderData.vehicle.model} in Pakistan. Check pricing, details and availability with a dealer.`):pageHead('Vehicle not found | Motori','The requested vehicle is not currently listed.'),
 component:Detail,
});
function Detail(){const {vehicle:v}=Route.useLoaderData();const specs=[['Brand',v.brand],['Model',v.model],['Body type',v.bodyType],['Fuel type',v.fuelType],['Engine',v.engine],['Transmission',v.transmission],['Power',v.horsepower],['Drivetrain',v.drivetrain],['Electric range',v.electricRange],['Battery capacity',v.batteryCapacity],['Seating',v.seatingCapacity?.toString()],['Warranty',v.warranty]];const similar=vehicles.filter(x=>x.id!==v.id&&(x.category===v.category||x.fuelType===v.fuelType)).slice(0,3);return <>
 <section className="relative min-h-[75svh] overflow-hidden bg-ink text-ink-foreground"><img src={vehicleImage(v)} alt="Illustrative automotive photograph, not the named model" className="absolute inset-0 h-full w-full object-cover"/><div className="hero-shade absolute inset-0"/><div className="relative mx-auto flex min-h-[75svh] max-w-[1600px] flex-col justify-end px-5 pb-14 pt-36 md:px-12"><Link to="/cars" search={{q:''}} className="mb-7 flex items-center gap-2 text-xs uppercase tracking-widest opacity-75"><ArrowLeft size={14}/> All cars</Link><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-signal">{v.brand} / {v.category}</p><h1 className="display-heading text-7xl md:text-9xl">{v.model}</h1><p className="mt-5 max-w-lg text-sm leading-7 opacity-80">{v.description}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild variant="signal" size="lg"><Link to="/compare" search={{cars:v.id}}>Compare model <ArrowRight/></Link></Button><Button asChild variant="inverse" size="lg"><Link to="/dealers">Find a dealer <ArrowRight/></Link></Button></div><p className="mt-8 text-[10px] uppercase tracking-widest opacity-60">Editorial image · not an image of the named model</p></div></section>
 <section className="mx-auto grid max-w-[1600px] gap-12 px-5 py-16 md:px-12 md:py-24 lg:grid-cols-[1fr_1.3fr]"><div><p className="mb-4 text-xs font-bold uppercase tracking-widest text-muted-foreground">MODEL OVERVIEW</p><h2 className="display-heading text-6xl md:text-7xl">THE DETAILS<br/>MATTER.</h2><p className="mt-6 max-w-md text-sm leading-7 text-muted-foreground">Specifications can differ by year, trim and market. Values not verified for this listing are marked “Not available.”</p><div className="mt-8 flex gap-3 border-t border-border pt-6"><Info size={20} className="shrink-0 text-signal"/><div><p className="text-xs font-bold uppercase">Price</p><p className="mt-1 text-xl font-semibold">{formatPrice(v.price)}</p><p className="mt-1 text-xs text-muted-foreground">Verify with dealer</p></div></div></div><div className="border-t border-border">{specs.map(([key,value])=><div key={key} className="grid grid-cols-2 gap-4 border-b border-border py-4 text-sm"><span className="text-muted-foreground">{key}</span><span className="font-semibold">{value||'Not available'}</span></div>)}</div></section>
 <section className="bg-secondary px-5 py-16 md:px-12 md:py-24"><div className="mx-auto max-w-[1600px]"><p className="mb-3 text-xs font-bold uppercase tracking-widest text-muted-foreground">KEEP EXPLORING</p><h2 className="display-heading mb-10 text-6xl">SIMILAR DRIVES.</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{similar.map(s=><VehicleCard key={s.id} vehicle={s}/>)}</div></div></section>
 </>}
