import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageIntro } from '@/components/auto/site-shell';
import { formatPrice, vehicles } from '@/data/vehicles';
import { pageHead } from '@/lib/seo';
export const Route=createFileRoute('/compare')({validateSearch:(s:Record<string,unknown>)=>({cars:typeof s['cars']==='string'?s['cars']:''}),head:()=>pageHead('Compare Cars in Pakistan | Motori','Compare up to four car models side by side with honest missing-data labels.'),component:Compare});
const fields:[string,(v:typeof vehicles[number])=>string|undefined][]=[['Price',v=>formatPrice(v.price)],['Body type',v=>v.bodyType],['Fuel type',v=>v.fuelType],['Transmission',v=>v.transmission],['Engine',v=>v.engine],['Power',v=>v.horsepower],['Torque',v=>v.torque],['Drivetrain',v=>v.drivetrain],['Ground clearance',v=>v.groundClearance],['Boot space',v=>v.bootSpace],['Seating',v=>v.seatingCapacity?.toString()],['Battery',v=>v.batteryCapacity],['EV range',v=>v.electricRange],['Charging',v=>v.chargingSpeed],['Warranty',v=>v.warranty]];
function Compare(){const {cars}=Route.useSearch();const [ids,setIds]=useState(()=>cars.split(',').filter(id=>vehicles.some(v=>v.id===id)).slice(0,4));const selected=ids.map(id=>vehicles.find(v=>v.id===id)).filter((v):v is typeof vehicles[number]=>Boolean(v));return <><PageIntro eyebrow="SIDE BY SIDE" title="COMPARE THE DETAILS." description="Look beyond the badge. Compare models on the things that matter to you; unknown values remain clearly marked."/><section className="mx-auto max-w-[1600px] px-5 py-12 md:px-12 md:py-20"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:Math.max(2,selected.length+Number(selected.length<4))}).map((_,i)=>{const v=selected[i];return <div key={i} className="relative min-h-28 border border-border bg-card p-5">{v?<><p className="text-xs uppercase text-muted-foreground">{v.brand}</p><p className="font-display text-3xl font-semibold uppercase">{v.model}</p><Button variant="ghost" size="icon" className="absolute right-2 top-2 size-9" aria-label={`Remove ${v.model}`} onClick={()=>setIds(ids.filter(id=>id!==v.id))}><X/></Button></>:<><label htmlFor={`compare-${i}`} className="mb-2 block text-xs font-bold uppercase text-muted-foreground">Add a model</label><select id={`compare-${i}`} className="w-full border border-input bg-background p-2 text-sm" value="" onChange={e=>setIds([...ids,e.target.value])}><option value="">Choose a car</option>{vehicles.filter(x=>!ids.includes(x.id)).map(x=><option key={x.id} value={x.id}>{x.brand} {x.model}</option>)}</select></>}</div>})}</div>{selected.length>0&&<div className="mt-10 overflow-x-auto border-t border-border"><table className="w-full min-w-[600px] text-left text-sm"><caption className="sr-only">Car model specifications comparison</caption><thead><tr><th className="w-40 py-4">Specification</th>{selected.map(v=><th key={v.id} className="min-w-40 py-4">{v.brand} {v.model}</th>)}</tr></thead><tbody>{fields.map(([label,get])=><tr key={label} className="border-t border-border"><th className="py-4 font-medium text-muted-foreground">{label}</th>{selected.map(v=><td key={v.id} className="py-4 font-semibold">{get(v)||'Not available'}</td>)}</tr>)}</tbody></table></div>}{selected.length===0&&<p className="mt-10 text-sm text-muted-foreground">Select two or more cars to compare their details.</p>}</section></>}
