import { useMemo, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, Search, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { VehicleCard } from './vehicle-card';
import { categories, vehicles } from '@/data/vehicles';
import type { Vehicle } from '@/types/vehicle';

export function CatalogGrid({initialQuery='',compact=false}: {initialQuery?:string;compact?:boolean}) {
 const [query,setQuery]=useState(initialQuery); const [category,setCategory]=useState('All'); const [brand,setBrand]=useState('All brands');
 const [selected,setSelected]=useState<string[]>([]); const [limit,setLimit]=useState(compact?6:12);
 const results=useMemo(()=>vehicles.filter(v=> (category==='All'||v.category===category||(category==='EV'&&v.fuelType==='Electric')||(category==='Hybrid'&&v.fuelType==='Hybrid')||(category==='Luxury'&&v.statuses.includes('PREMIUM'))||(category==='Commercial'&&v.statuses.includes('COMMERCIAL'))) && (brand==='All brands'||v.brand===brand) && `${v.brand} ${v.model} ${v.category} ${v.fuelType}`.toLowerCase().includes(query.toLowerCase())),[query,category,brand]);
 const toggle=(v:Vehicle)=>setSelected(s=>s.includes(v.id)?s.filter(id=>id!==v.id):s.length<4?[...s,v.id]:s);
 return <div><div className="grid gap-3 border-y border-border py-5 md:grid-cols-[minmax(0,1fr)_190px] md:items-center"><label className="flex h-12 items-center gap-3 border border-input bg-card px-4"><Search size={17} className="text-muted-foreground"/><input aria-label="Search make or model" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search make or model" className="h-full min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"/>{query&&<Button variant="ghost" size="icon" className="size-8" aria-label="Clear search" onClick={()=>setQuery('')}><X/></Button>}</label><select aria-label="Filter by brand" value={brand} onChange={e=>setBrand(e.target.value)} className="h-12 border border-input bg-card px-3 text-sm"><option>All brands</option>{[...new Set(vehicles.map(v=>v.brand))].sort().map(b=><option key={b}>{b}</option>)}</select></div><div className="my-5 flex gap-2 overflow-x-auto pb-2">{categories.map(c=><Button key={c} variant={category===c?'default':'outline'} size="sm" onClick={()=>{setCategory(c);setLimit(compact?6:12)}} className="h-9 shrink-0 rounded-none px-4 text-xs">{c}</Button>)}</div><div className="mb-5 flex items-center justify-between text-xs text-muted-foreground"><span>{results.length} models in view</span><span>Pricing subject to dealer confirmation</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{results.slice(0,limit).map(v=><VehicleCard key={v.id} vehicle={v} selected={selected.includes(v.id)} onCompare={toggle}/>)}</div>{results.length===0&&<p className="py-16 text-center text-muted-foreground">No matches. Try another make or category.</p>}{results.length>limit&&<div className="mt-8 text-center"><Button variant="outline" size="lg" onClick={()=>setLimit(limit+12)}>Show more cars <ArrowRight/></Button></div>}{compact&&<div className="mt-8 text-center"><Button asChild variant="outline" size="lg"><Link to="/cars">Browse all cars <ArrowRight/></Link></Button></div>}{selected.length>0&&<div className="fixed bottom-20 left-1/2 z-40 flex w-[min(92vw,550px)] -translate-x-1/2 items-center justify-between gap-3 bg-ink p-3 text-ink-foreground shadow-2xl md:bottom-7"><span className="pl-2 text-xs">{selected.length} selected <span className="hidden sm:inline">/ up to 4 cars</span></span><Button asChild variant="signal" size="sm"><Link to="/compare" search={{cars:selected.join(',')}}>Compare cars <ArrowRight/></Link></Button></div>}</div>;
}
