/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DealersRouteImport } from './routes/dealers'
import { Route as EvRouteImport } from './routes/ev'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as NewRouteImport } from './routes/new'
import { Route as CarsBrandModelRouteImport } from './routes/cars.$brand.$model'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersRoute = DealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const EvRoute = EvRouteImport.update({
  id: '/ev',
  path: '/ev',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsBrandModelRoute = CarsBrandModelRouteImport.update({
  id: '/$brand/$model',
  path: '/$brand/$model',
  getParentRoute: () => CarsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/dealers': typeof DealersRoute
  '/ev': typeof EvRoute
  '/finance': typeof FinanceRoute
  '/new': typeof NewRoute
  '/cars/$brand/$model': typeof CarsBrandModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/dealers': typeof DealersRoute
  '/ev': typeof EvRoute
  '/finance': typeof FinanceRoute
  '/new': typeof NewRoute
  '/cars/$brand/$model': typeof CarsBrandModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/dealers': typeof DealersRoute
  '/ev': typeof EvRoute
  '/finance': typeof FinanceRoute
  '/new': typeof NewRoute
  '/cars/$brand/$model': typeof CarsBrandModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/cars'
    | '/compare'
    | '/dealers'
    | '/ev'
    | '/finance'
    | '/new'
    | '/cars/$brand/$model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/cars'
    | '/compare'
    | '/dealers'
    | '/ev'
    | '/finance'
    | '/new'
    | '/cars/$brand/$model'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/cars'
    | '/compare'
    | '/dealers'
    | '/ev'
    | '/finance'
    | '/new'
    | '/cars/$brand/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  CarsRoute: typeof CarsRouteWithChildren
  CompareRoute: typeof CompareRoute
  DealersRoute: typeof DealersRoute
  EvRoute: typeof EvRoute
  FinanceRoute: typeof FinanceRoute
  NewRoute: typeof NewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers': {
      id: '/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof DealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev': {
      id: '/ev'
      path: '/ev'
      fullPath: '/ev'
      preLoaderRoute: typeof EvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$brand/$model': {
      id: '/cars/$brand/$model'
      path: '/$brand/$model'
      fullPath: '/cars/$brand/$model'
      preLoaderRoute: typeof CarsBrandModelRouteImport
      parentRoute: typeof CarsRoute
    }
  }
}

interface CarsRouteChildren {
  CarsBrandModelRoute: typeof CarsBrandModelRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsBrandModelRoute: CarsBrandModelRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  CarsRoute: CarsRouteWithChildren,
  CompareRoute: CompareRoute,
  DealersRoute: DealersRoute,
  EvRoute: EvRoute,
  FinanceRoute: FinanceRoute,
  NewRoute: NewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
